### ISSUE TITLE
Errors in setup_Casa.log

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/casa#107]
The following appears at the bottom of file once the app is installed. It does not seem to affect the app functionality fortunately

```
08:49:08 12/20/19 Running: /bin/systemctl restart oxauth
08:50:02 12/20/19 Run: /bin/systemctl restart oxauth with result code: 0
08:50:02 12/20/19 Running: /bin/systemctl start casa
08:50:23 12/20/19 Run: /bin/systemctl start casa with result code: 0
08:50:23 12/20/19 Saving properties to /install/community-edition-setup/setup_casa.properties.last
08:50:23 12/20/19 Error saving properties
08:50:23 12/20/19 Traceback (most recent call last):
  File "/install/community-edition-setup/setup.py", line 3561, in save_properties
    self.run(['openssl', 'enc', '-aes-256-cbc', '-in', prop_fn, '-out', prop_fn+'.enc', '-k', self.oxtrust_admin_password])
  File "/install/community-edition-setup/setup.py", line 3487, in run
    log_arg = ' '.join(args) if type(args) is list else args
TypeError: sequence item 8: expected string, NoneType found
```

**Comment by mbaser** [comment]
Implemented in commit https://github.com/GluuFederation/casa/commit/b5625547a4ba125b435d4158affaf78d31223e22
