### ISSUE TITLE
Cert-authn plugin shows error page when cert validation fails

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/casa#176]
When enrolling, if the user certificate does not pass validations an NPE is thrown here: https://github.com/GluuFederation/casa/blob/version_4.3.0/plugins/cert-authn/src/main/java/org/gluu/casa/plugins/cert/vm/CertAuthenticationViewModel.java#L121

Which ends up in the 500 error jetty page. A proper error page should be shown.

Example stack trace:

```
ERROR oxauth.cert.validation.PathCertificateVerifier PathCertificateVerifier.java:127- Failed to build certificate path
java.security.cert.CertPathBuilderException: No issuer certificate for certificate in certification path found.
    at org.bouncycastle.jce.provider.PKIXCertPathBuilderSpi_8.engineBuild(Unknown Source) ~[bcprov-jdk15on-1.69.jar:1.69.0]
    at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297) ~[?:?]
    at org.gluu.oxauth.cert.validation.PathCertificateVerifier.verifyCertificate(PathCertificateVerifier.java:182) ~[?:?]
    at org.gluu.oxauth.cert.validation.PathCertificateVerifier.verifyCertificate(PathCertificateVerifier.java:112) ~[?:?]
    at org.gluu.oxauth.cert.validation.PathCertificateVerifier.validate(PathCertificateVerifier.java:74) ~[?:?]
    at org.gluu.casa.plugins.cert.service.CertService.validate(CertService.java:119) ~[?:?]
    at org.gluu.casa.plugins.cert.vm.CertAuthenticationViewModel.processCert(CertAuthenticationViewModel.java:166) ~[?:?]
    at org.gluu.casa.plugins.cert.vm.CertAuthenticationViewModel.init(CertAuthenticationViewModel.java:115) ~[?:?]
```

**Comment by jgomer2001** [comment]
https://github.com/GluuFederation/casa/commit/b3213aa23c4a2ad48baa931a1925a5ceaed47c4b
