### ISSUE TITLE
Not able to add duo credentials in casa.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/casa#215]
### Describe the issue
Not able to add duo credentials in casa.

### How to reproduce

1. Go to casa ui
2. Enable duo authentication method.
3. Go to credentials page.
4. try to duo credentials.

### Expected behaviour 

duo credentials or device must be added

### Actual behaviour 

the UI reloads to enrollment 

### config

Gluu-casa 4.4.1 .

OS Ubuntu 20.04

### logs

```
27-06 18:31:39.553 INFO  [casaScheduler_Worker-4] gluu.casa.core.ExtensionsManager ExtensionsManager.java:331- Plugin duo-plugin started
27-06 18:31:39.565 ERROR [casaScheduler_Worker-4] casa.plugins.duo.DuoService DuoService.java:86- null
java.lang.NullPointerException: null
        at org.gluu.casa.plugins.duo.DuoService.reloadConfiguration(DuoService.java:77) ~[?:?]
        at org.gluu.casa.plugins.duo.DuoService.<init>(DuoService.java:44) ~[?:?]
        at org.gluu.casa.plugins.duo.DuoService.getInstance(DuoService.java:52) ~[?:?]
        at org.gluu.casa.plugins.duo.extensions.DuoExtension.<init>(DuoExtension.java:33) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at java.lang.Class.newInstance(Class.java:584) ~[?:?]
        at org.pf4j.DefaultExtensionFactory.create(DefaultExtensionFactory.java:38) ~[pf4j-3.2.0.jar:3.2.0]
        at org.gluu.casa.core.plugin.SingletonExtensionFactory.create(SingletonExtensionFactory.java:26) ~[classes/:?]
        at org.pf4j.ExtensionWrapper.getExtension(ExtensionWrapper.java:37) ~[pf4j-3.2.0.jar:3.2.0]
        at org.pf4j.AbstractPluginManager.getExtensions(AbstractPluginManager.java:927) ~[pf4j-3.2.0.jar:3.2.0]
        at org.pf4j.AbstractPluginManager.getExtensions(AbstractPluginManager.java:552) ~[pf4j-3.2.0.jar:3.2.0]
        at org.gluu.casa.core.ExtensionsManager.parsePluginAuthnMethodExtensions(ExtensionsManager.java:352) ~[classes/:?]
        at org.gluu.casa.core.ExtensionsManager.startPlugin(ExtensionsManager.java:332) ~[classes/:?]
        at org.gluu.casa.core.ExtensionsManager.updatePlugins(ExtensionsManager.java:181) ~[classes/:?]
        at org.gluu.casa.core.ExtensionsManager$Proxy$_$$_WeldClientProxy.updatePlugins(Unknown Source) ~[classes/:?]
        at org.gluu.casa.timer.FSPluginChecker.jobToBeExecuted(FSPluginChecker.java:129) ~[classes/:?]
        at org.quartz.core.QuartzScheduler.notifyJobListenersToBeExecuted(QuartzScheduler.java:1927) ~[quartz-2.3.2.jar:?]
        at org.quartz.core.JobRunShell.notifyListenersBeginning(JobRunShell.java:324) ~[quartz-2.3.2.jar:?]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:173) ~[quartz-2.3.2.jar:?]
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.2.jar:?]
27-06 18:31:39.592 INFO  [casaScheduler_Worker-4] gluu.casa.core.ExtensionsManager ExtensionsManager.java:354- Plugin extends org.gluu.casa.extension.AuthnMethod at 1 point(s)

```

**Comment by nynymike** [comment]
This should not block release of 4.4.1

**Comment by maduvena** [comment]
Hi @MohitMaliFtechiz - can you check `admin_api_ikey` and `admin_api_skey` in `/etc/certs/duo_creds.json` 
It should be configured as specified in [here](https://github.com/GluuFederation/casa/blob/version_4.2.2/plugins/duo/extras/duo_creds.json)

**Comment by MohitMaliFtechiz** [comment]
hi @maduvena  yes it was error of missing ``` admin_api_ikey ```  and ``` admin_api_skey ``` in ``` /etc/certs/duo_creds.json ```. i am able to register the user in casa now.  
![Screenshot from 2022-08-01 12-54-43](https://user-images.githubusercontent.com/34593983/182096218-2810f294-18db-4c9e-b41a-ad9e7c9c476d.png)
Closing the issue.
