### ISSUE TITLE
Release RestEasy connections when invoking oxd http methods

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/casa#6]
Casa uses the default underlying `httpEngine` of RestEasy Client Framework.

From the docs:

> if the result of an invocation is an instance of Response, then Response.close() method must be used to released the connection.

At times we are obtaining the following when reading `CommandResponse.class` instances:
```
javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:290) ~[resteasy-client-3.0.21.Final.jar:3.0.21.Final]
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:435) ~[resteasy-client-3.0.21.Final.jar:3.0.21.Final]
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.post(ClientInvocationBuilder.java:199) ~[resteasy-client-3.0.21.Final.jar:3.0.21.Final]
	at org.gluu.credmanager.services.OxdService.restResponse(OxdService.java:343) ~[classes/:?]
	at org.gluu.credmanager.services.OxdService.getPAT(OxdService.java:328) ~[classes/:?]
	at org.gluu.credmanager.services.OxdService.getTokens(OxdService.java:206) ~[classes/:?]
	at org.gluu.credmanager.services.OxdService$Proxy$_$$_WeldClientProxy.getTokens(Unknown Source) ~[classes/:?]
	at org.gluu.credmanager.core.navigation.HomeInitiator.doInit(HomeInitiator.java:101) [classes/:?]
...
Caused by: java.lang.IllegalStateException: Invalid use of BasicClientConnManager: connection still allocated.
Make sure to release the connection before allocating another one.
	at org.apache.http.impl.conn.BasicClientConnectionManager.getConnection(BasicClientConnectionManager.java:162) ~[httpclient-4.2.3.jar:4.2.3]
	at org.apache.http.impl.conn.BasicClientConnectionManager$1.getConnection(BasicClientConnectionManager.java:139) ~[httpclient-4.2.3.jar:4.2.3]
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:456) ~[httpclient-4.2.3.jar:4.2.3]
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906) ~[httpclient-4.2.3.jar:4.2.3]
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805) ~[httpclient-4.2.3.jar:4.2.3]
	at org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine.invoke(ApacheHttpClient4Engine.java:286) ~[resteasy-client-3.0.21.Final.jar:3.0.21.Final]
	... 70 more
```

Apart from releasing connections explicitly, we have to user safer `ThreadSafeClientConnManager`

**Comment by jgomer2001** [comment]
By default casa will use [PoolingClientConnectionManager](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/conn/PoolingClientConnectionManager.html).

To revert to resteasy default (SingleClientConnManager), pass variable `httpclient.DefaultClientConnManager` with any value, eg. `-Dhttpclient.DefaultClientConnManager=true`.
